# Generated by Django 5.2.6 on 2025-09-29 16:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0017_learnerregistration_is_revoked'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('affiliate_price', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10)),
                ('learner_price', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='superadmin.course')),
            ],
            options={
                'verbose_name': 'Course Pricing',
                'verbose_name_plural': 'Course Pricing',
            },
        ),
    ]
