# Generated by Django 5.2.6 on 2025-09-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_affiliatecoursepricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliateCoursePricing',
        ),
    ]
