# Generated by Django 5.2.6 on 2025-09-29 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_invoicepayment'),
        ('superadmin', '0017_learnerregistration_is_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvoicedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('unit_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('course_title_snapshot', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.invoicepayment')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_item', to='superadmin.learnerregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice'], name='pricing_inv_invoice_368ee7_idx'), models.Index(fields=['registration'], name='pricing_inv_registr_59e5a8_idx')],
            },
        ),
    ]
