# Generated by Django 5.2.6 on 2025-10-16 11:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_invoicepayment_issued_at_invoiceditem'),
        ('superadmin', '0034_increase_course_certificate_number_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_certification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='superadmin.isocertification')),
            ],
            options={
                'verbose_name': 'ISO Pricing',
                'verbose_name_plural': 'ISO Pricing',
            },
        ),
    ]
