# Generated by Django 5.2.6 on 2025-10-16 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_isopricing'),
        ('superadmin', '0035_isopaymentsession_isoissuedcertificatepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoInvoicedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('unit_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('iso_standard_snapshot', models.CharField(max_length=255)),
                ('management_system_snapshot', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=50)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_item', to='superadmin.isoissuedcertificate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_items', to='pricing.invoicepayment')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice'], name='pricing_iso_invoice_0921f8_idx'), models.Index(fields=['certificate'], name='pricing_iso_certifi_bfd84c_idx')],
            },
        ),
    ]
