# Generated by Django 5.2.6 on 2025-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=50)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('businesses', models.ManyToManyField(blank=True, help_text='Assign this course to one or more businesses.', related_name='courses', to='superadmin.business')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
