# Generated by Django 5.2.6 on 2025-09-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_learnerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
