# Generated by Django 5.2.6 on 2025-09-25 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_business_is_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Upload a PNG template used to render certificates.', null=True, upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total credit hours for this course.'),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='training_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='training_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
