# Generated by Django 5.2.6 on 2025-09-25 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_course_certificate_template_course_credit_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total credit hours (e.g., 0.5, 1.6).', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
