# Generated by Django 5.2.6 on 2025-09-25 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_alter_course_credit_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Upload a PNG template used to render certificates.', null=True, upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(['png, jpg, svg'])]),
        ),
    ]
