# Generated by Django 5.2.6 on 2025-09-25 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_course_certificate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='Upload a certificate template (PNG, JPG, or SVG).', null=True, upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
