# Generated by Django 5.2.6 on 2025-09-25 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_alter_course_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_sample',
            field=models.FileField(blank=True, help_text='Upload a sample learner certificate (PNG, JPG, or SVG).', null=True, upload_to='certificate_samples/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
