# Generated by Django 5.2.6 on 2025-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_course_certificate_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregistration',
            name='certificate_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated certificate number (e.g., AB12345).', max_length=7, null=True, unique=True),
        ),
    ]
