# Generated by Django 5.2.6 on 2025-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_learnerregistration_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Optional JSON layout (relative positions 0..1) like: {"name":{"x":0.50,"y":0.45,"fs":64,"color":"#0B2545","anchor":"mm"},"course":{"x":0.50,"y":0.55,"fs":40,"color":"#0B2545","anchor":"mm"},"dates":{"x":0.50,"y":0.62,"fs":28,"color":"#0B2545","anchor":"mm"},"number":{"x":0.88,"y":0.90,"fs":20,"color":"#111827","anchor":"rs"},"qrcode":{"x":0.12,"y":0.88,"size":220,"anchor":"ls"}}'),
        ),
    ]
