# Generated by Django 5.2.6 on 2025-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_alter_course_certificate_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, help_text='Short paragraph describing the course. Can be printed on certificates.'),
        ),
        migrations.AddField(
            model_name='course',
            name='show_course_description_on_certificate',
            field=models.BooleanField(default=False, help_text='If enabled, the course_description will be printed on the certificate after the learner name.'),
        ),
    ]
