# Generated by Django 5.2.6 on 2025-09-26 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_course_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='iascb_course_number',
            field=models.CharField(blank=True, db_index=True, help_text='IASCB Course No. (e.g., I-1547).', max_length=20, validators=[django.core.validators.RegexValidator('^I-\\d{3,6}$', 'Use format I-#### (e.g., I-1547).')]),
        ),
    ]
