# Generated by Django 5.2.6 on 2025-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_course_iascb_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_style',
            field=models.CharField(choices=[('lead', 'Lead Auditor'), ('internal', 'Internal Auditor'), ('other', 'Other Certificates')], default='lead', help_text='Select a layout preset. You can fine-tune positions in code presets.', max_length=20),
        ),
    ]
