# Generated by Django 5.2.6 on 2025-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_course_certificate_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_title_override',
            field=models.TextField(blank=True, help_text="Optional alternate title for certificate. Supports line breaks to split across multiple lines (e.g., 'ISO 9001:2015\\nLead Auditor Course')."),
        ),
    ]
