# Generated by Django 5.2.6 on 2025-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_course_certificate_title_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregistration',
            name='is_revoked',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, verification by code/QR should fail.'),
        ),
    ]
