# Generated by Django 5.2.6 on 2025-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_drop_business_timezone_and_nextinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(help_text='e.g., ISO 45001:2018', max_length=120)),
                ('management_system', models.CharField(help_text='e.g., OHS Mgt system', max_length=120)),
                ('iascb_accreditation_no', models.CharField(blank=True, max_length=120, verbose_name='IASCB Accreditation No')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ISO Certification',
                'verbose_name_plural': 'ISO Certifications',
                'ordering': ['standard'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_style',
            field=models.CharField(choices=[('lead', 'Lead Auditor'), ('internal', 'Internal Auditor'), ('other', 'Other Certificates'), ('osha', 'OSHA')], default='lead', help_text='Select a layout preset. You can fine-tune positions in code presets.', max_length=20),
        ),
    ]
