# Generated by Django 5.2.6 on 2025-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_isocertification_alter_course_certificate_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='isocertification',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='iso_certifications', to='superadmin.business'),
        ),
    ]
