# Generated by Django 5.2.6 on 2025-10-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_isocertification_businesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoIssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certified_business_name', models.CharField(max_length=255)),
                ('certified_business_address', models.TextField()),
                ('scope_text', models.TextField(help_text='Line breaks will be preserved.')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('certificate_number', models.CharField(db_index=True, max_length=6, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('surveillance_1_date', models.DateField()),
                ('surveillance_2_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='iso_qr/')),
                ('is_revoked', models.BooleanField(default=False)),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certs', to='superadmin.isocertification')),
                ('issuer_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_iso_certs', to='superadmin.business')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
