# Generated by Django 5.2.6 on 2025-10-01 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_isoissuedcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='isocertification',
            name='template_image',
            field=models.ImageField(blank=True, help_text='Upload a PNG base template for this ISO certificate.', null=True, upload_to='iso_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
