# Generated by Django 5.2.6 on 2025-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_isocertification_template_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='isocertification',
            name='iso_pdf_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Layout for ISO PDF (pixels or percents where noted). Examples: {"fs_business": 210, "fs_iso": 300, "fs_body": 102, "fs_small": 66,"y_start": 460, "gap_after_business": 52, "gap_after_addr": 250,"col_side_margin_px": 260, "col_gap_px": 24, "row_gap": 0.80,"qr_size": 520, "x_qr": 1680, "y_qr": 2700,"legal_start_pct": 0.70,}'),
        ),
    ]
