# Generated by Django 5.2.6 on 2025-10-09 15:18

import django.core.validators
import users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_isocertification_iso_pdf_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_sample',
            field=models.FileField(blank=True, help_text='Upload a sample learner certificate (PNG, JPG, or SVG).', null=True, storage=users.storage_backends.CertSampleStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='Upload a certificate template (PNG, JPG, or SVG).', null=True, storage=users.storage_backends.CertTemplateStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='isocertification',
            name='template_image',
            field=models.ImageField(blank=True, help_text='Upload a PNG base template for this ISO certificate.', null=True, storage=users.storage_backends.IsoTemplateStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
