# Generated by Django 5.2.6 on 2025-10-09 15:29

import users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_alter_course_certificate_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerregistration',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, storage=users.storage_backends.CertOutputStorage(), upload_to=''),
        ),
    ]
