# Generated by Django 5.2.6 on 2025-10-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0026_alter_learnerregistration_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='advance_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='atp_number',
            field=models.CharField(blank=True, db_index=True, help_text='AA000 format.', max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='atp_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='atp_qr/'),
        ),
    ]
