# Generated by Django 5.2.6 on 2025-10-10 09:25

import django.core.validators
import users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0027_business_advance_payment_business_atp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auth_cert_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Layout in relative positions (0..1). Keys:\n  - "name"   {"x":0.50,"y":0.45,"fs":64}\n  - "number" {"x":0.50,"y":0.55,"fs":40}\n  - "date"   {"x":0.50,"y":0.62,"fs":28}\n  - "qrcode" {"x":0.85,"y":0.85,"size":220}\nAll coordinates are relative to the image width/height.'),
        ),
        migrations.AddField(
            model_name='business',
            name='auth_cert_template',
            field=models.FileField(blank=True, help_text='Upload base image (PNG/JPG) for the Authorization Certificate.', null=True, storage=users.storage_backends.CertTemplateStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
