# Generated by Django 5.2.6 on 2025-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0028_business_auth_cert_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregistration',
            name='certificate_shared_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
