# Generated by Django 5.2.6 on 2025-10-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0031_paymentsession_learnerregistrationpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isoissuedcertificate',
            name='issuer_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_iso_certs', to='superadmin.business'),
        ),
    ]
