# Generated by Django 5.2.6 on 2025-10-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0032_make_issuer_business_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isoissuedcertificate',
            name='certificate_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
