# Generated by Django 5.2.6 on 2025-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_increase_certificate_number_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerregistration',
            name='certificate_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated certificate number (e.g., AB12345) or legacy certificate number.', max_length=50, null=True, unique=True),
        ),
    ]
