# Generated by Django 5.2.6 on 2025-10-16 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0034_increase_course_certificate_number_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_payment_sessions', to='superadmin.business')),
                ('iso_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='superadmin.isocertification')),
            ],
            options={
                'verbose_name': 'ISO Payment Session',
                'verbose_name_plural': 'ISO Payment Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IsoIssuedCertificatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='superadmin.isoissuedcertificate')),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='superadmin.isopaymentsession')),
            ],
            options={
                'verbose_name': 'ISO Certificate Payment',
                'verbose_name_plural': 'ISO Certificate Payments',
            },
        ),
    ]
