# Generated by Django 5.2.6 on 2025-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_isopaymentsession_isoissuedcertificatepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregistration',
            name='certificate_expiry_date',
            field=models.DateField(blank=True, help_text='Certificate expiry date (for legacy certificates with expiry)', null=True),
        ),
    ]
