# Generated by Django 5.2.6 on 2025-10-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0036_add_certificate_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, help_text="Optional section heading (e.g., 'Year 1: Foundational Knowledge')", max_length=255)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order for this section')),
                ('credits', models.PositiveIntegerField(default=120, help_text='Credits for this section (e.g., 120)')),
                ('tqt_hours', models.PositiveIntegerField(default=1200, help_text='Total Qualification Time in hours (e.g., 1200)')),
                ('glh_hours', models.PositiveIntegerField(default=600, help_text='Guided Learning Hours (e.g., 600)')),
                ('remarks', models.CharField(default='Grade Pass', help_text="Remarks text (e.g., 'Grade Pass')", max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='superadmin.course')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QualificationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ref', models.CharField(help_text="Unit reference code (e.g., 'AGE0001-1')", max_length=50)),
                ('unit_title', models.CharField(help_text="Unit title (e.g., 'Introduction to Agricultural Engineering')", max_length=500)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order for this unit within the section')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='superadmin.qualificationsection')),
            ],
            options={
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
