# Generated by Django 5.2.6 on 2025-10-26 13:14

import django.core.validators
import users.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0037_qualificationsection_qualificationunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_sample',
            field=models.FileField(blank=True, help_text='Upload a sample learner certificate (PDF).', null=True, storage=users.storage_backends.CertSampleStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
