# Generated by Django 5.2.6 on 2025-10-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0038_update_certificate_sample_to_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregistration',
            name='learner_number',
            field=models.CharField(blank=True, db_index=True, help_text='6-digit unique learner number (256001-999999)', max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='learnerregistration',
            name='certificate_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated certificate number (e.g., ICTQ265788) or legacy certificate number.', max_length=50, null=True, unique=True),
        ),
    ]
