# Generated by Django 5.2.6 on 2025-10-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0039_add_learner_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
    ]
