# Generated by Django 5.2.6 on 2025-10-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0040_add_duration_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregistration',
            name='awarded_date',
            field=models.DateField(blank=True, help_text='Date to display on certificate as the awarded date (max 60 days in the past, no future dates)', null=True),
        ),
    ]
