# Generated by Django 5.2.6 on 2025-12-09 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0041_add_awarded_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learnerregistration',
            unique_together={('course', 'learner', 'business')},
        ),
    ]
