# Generated by Django 5.0.7 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0043_businesscoursediscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualificationunit",
            name="credits",
            field=models.PositiveIntegerField(default=0, help_text="Credits for this unit (e.g., 10)"),
        ),
        migrations.AddField(
            model_name="qualificationunit",
            name="glh_hours",
            field=models.PositiveIntegerField(default=0, help_text="Guided Learning Hours for this unit (e.g., 40)"),
        ),
    ]
