# Generated by Django 5.2.6 on 2025-10-09 13:18

import django.core.validators
import learners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercertificate',
            name='file',
            field=models.FileField(help_text='PNG, JPG, or PDF', upload_to=learners.models.certificate_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])]),
        ),
    ]
